
struct PhoneCountryCode {
    let code: Int
    let countryCode: String
    let countryName: String
}

let phoneCountryCodes: [PhoneCountryCode] = [
    PhoneCountryCode(code: 93, countryCode: "af", countryName: "Afghanistan"),
    PhoneCountryCode(code: 355, countryCode: "al", countryName: "Albania"),
    PhoneCountryCode(code: 213, countryCode: "dz", countryName: "Algeria"),
    PhoneCountryCode(code: 376, countryCode: "ad", countryName: "Andorra"),
    PhoneCountryCode(code: 244, countryCode: "ao", countryName: "Angola"),
    PhoneCountryCode(code: 54, countryCode: "ar", countryName: "Argentina"),
    PhoneCountryCode(code: 374, countryCode: "am", countryName: "Armenia"),
    PhoneCountryCode(code: 297, countryCode: "aw", countryName: "Aruba"),
    PhoneCountryCode(code: 61, countryCode: "au", countryName: "Australia"),
    PhoneCountryCode(code: 43, countryCode: "at", countryName: "Austria"),
    PhoneCountryCode(code: 994, countryCode: "az", countryName: "Azerbaijan"),
    PhoneCountryCode(code: 973, countryCode: "bh", countryName: "Bahrain"),
    PhoneCountryCode(code: 880, countryCode: "bd", countryName: "Bangladesh"),
    PhoneCountryCode(code: 375, countryCode: "by", countryName: "Belarus"),
    PhoneCountryCode(code: 32, countryCode: "be", countryName: "Belgium"),
    PhoneCountryCode(code: 501, countryCode: "bz", countryName: "Belize"),
    PhoneCountryCode(code: 229, countryCode: "bj", countryName: "Benin"),
    PhoneCountryCode(code: 975, countryCode: "bt", countryName: "Bhutan"),
    PhoneCountryCode(code: 591, countryCode: "bo", countryName: "Bolivia"),
    PhoneCountryCode(code: 387, countryCode: "ba", countryName: "Bosnia and Herzegovina"),
    PhoneCountryCode(code: 267, countryCode: "bw", countryName: "Botswana"),
    PhoneCountryCode(code: 55, countryCode: "br", countryName: "Brazil"),
    PhoneCountryCode(code: 246, countryCode: "io", countryName: "British Indian Ocean Territory"),
    PhoneCountryCode(code: 673, countryCode: "bn", countryName: "Brunei"),
    PhoneCountryCode(code: 359, countryCode: "bg", countryName: "Bulgaria"),
    PhoneCountryCode(code: 226, countryCode: "bf", countryName: "Burkina Faso"),
    PhoneCountryCode(code: 257, countryCode: "bi", countryName: "Burundi"),
    PhoneCountryCode(code: 855, countryCode: "kh", countryName: "Cambodia"),
    PhoneCountryCode(code: 237, countryCode: "cm", countryName: "Cameroon"),
    PhoneCountryCode(code: 1, countryCode: "ca", countryName: "Canada"),
    PhoneCountryCode(code: 238, countryCode: "cv", countryName: "Cape Verde"),
    PhoneCountryCode(code: 599, countryCode: "bq", countryName: "Caribbean Netherlands"),
    PhoneCountryCode(code: 236, countryCode: "cf", countryName: "Central African Republic"),
    PhoneCountryCode(code: 235, countryCode: "td", countryName: "Chad"),
    PhoneCountryCode(code: 56, countryCode: "cl", countryName: "Chile"),
    PhoneCountryCode(code: 86, countryCode: "cn", countryName: "China"),
    PhoneCountryCode(code: 57, countryCode: "co", countryName: "Colombia"),
    PhoneCountryCode(code: 269, countryCode: "km", countryName: "Comoros"),
    PhoneCountryCode(code: 243, countryCode: "cd", countryName: "Congo"),
    PhoneCountryCode(code: 242, countryCode: "cg", countryName: "Congo"),
    PhoneCountryCode(code: 506, countryCode: "cr", countryName: "Costa Rica"),
    PhoneCountryCode(code: 225, countryCode: "ci", countryName: "Côte d’Ivoire"),
    PhoneCountryCode(code: 385, countryCode: "hr", countryName: "Croatia"),
    PhoneCountryCode(code: 53, countryCode: "cu", countryName: "Cuba"),
    PhoneCountryCode(code: 599, countryCode: "cw", countryName: "Curaçao"),
    PhoneCountryCode(code: 357, countryCode: "cy", countryName: "Cyprus"),
    PhoneCountryCode(code: 420, countryCode: "cz", countryName: "Czech Republic"),
    PhoneCountryCode(code: 45, countryCode: "dk", countryName: "Denmark"),
    PhoneCountryCode(code: 253, countryCode: "dj", countryName: "Djibouti"),
    PhoneCountryCode(code: 1, countryCode: "do", countryName: "Dominican Republic"),
    PhoneCountryCode(code: 593, countryCode: "ec", countryName: "Ecuador"),
    PhoneCountryCode(code: 20, countryCode: "eg", countryName: "Egypt"),
    PhoneCountryCode(code: 503, countryCode: "sv", countryName: "El Salvador"),
    PhoneCountryCode(code: 240, countryCode: "gq", countryName: "Equatorial Guinea"),
    PhoneCountryCode(code: 291, countryCode: "er", countryName: "Eritrea"),
    PhoneCountryCode(code: 372, countryCode: "ee", countryName: "Estonia"),
    PhoneCountryCode(code: 251, countryCode: "et", countryName: "Ethiopia"),
    PhoneCountryCode(code: 679, countryCode: "fj", countryName: "Fiji"),
    PhoneCountryCode(code: 358, countryCode: "fi", countryName: "Finland"),
    PhoneCountryCode(code: 33, countryCode: "fr", countryName: "France"),
    PhoneCountryCode(code: 594, countryCode: "gf", countryName: "French Guiana"),
    PhoneCountryCode(code: 689, countryCode: "pf", countryName: "French Polynesia"),
    PhoneCountryCode(code: 241, countryCode: "ga", countryName: "Gabon"),
    PhoneCountryCode(code: 220, countryCode: "gm", countryName: "Gambia"),
    PhoneCountryCode(code: 995, countryCode: "ge", countryName: "Georgia"),
    PhoneCountryCode(code: 49, countryCode: "de", countryName: "Germany"),
    PhoneCountryCode(code: 233, countryCode: "gh", countryName: "Ghana"),
    PhoneCountryCode(code: 30, countryCode: "gr", countryName: "Greece"),
    PhoneCountryCode(code: 590, countryCode: "gp", countryName: "Guadeloupe"),
    PhoneCountryCode(code: 502, countryCode: "gt", countryName: "Guatemala"),
    PhoneCountryCode(code: 224, countryCode: "gn", countryName: "Guinea"),
    PhoneCountryCode(code: 245, countryCode: "gw", countryName: "Guinea-Bissau"),
    PhoneCountryCode(code: 592, countryCode: "gy", countryName: "Guyana"),
    PhoneCountryCode(code: 509, countryCode: "ht", countryName: "Haiti"),
    PhoneCountryCode(code: 504, countryCode: "hn", countryName: "Honduras"),
    PhoneCountryCode(code: 852, countryCode: "hk", countryName: "Hong Kong"),
    PhoneCountryCode(code: 36, countryCode: "hu", countryName: "Hungary"),
    PhoneCountryCode(code: 354, countryCode: "is", countryName: "Iceland"),
    PhoneCountryCode(code: 91, countryCode: "in", countryName: "India"),
    PhoneCountryCode(code: 62, countryCode: "id", countryName: "Indonesia"),
    PhoneCountryCode(code: 98, countryCode: "ir", countryName: "Iran"),
    PhoneCountryCode(code: 964, countryCode: "iq", countryName: "Iraq"),
    PhoneCountryCode(code: 353, countryCode: "ie", countryName: "Ireland"),
    PhoneCountryCode(code: 972, countryCode: "il", countryName: "Israel"),
    PhoneCountryCode(code: 39, countryCode: "it", countryName: "Italy"),
    PhoneCountryCode(code: 81, countryCode: "jp", countryName: "Japan"),
    PhoneCountryCode(code: 962, countryCode: "jo", countryName: "Jordan"),
    PhoneCountryCode(code: 7, countryCode: "kz", countryName: "Kazakhstan"),
    PhoneCountryCode(code: 254, countryCode: "ke", countryName: "Kenya"),
    PhoneCountryCode(code: 686, countryCode: "ki", countryName: "Kiribati"),
    PhoneCountryCode(code: 383, countryCode: "xk", countryName: "Kosovo"),
    PhoneCountryCode(code: 965, countryCode: "kw", countryName: "Kuwait"),
    PhoneCountryCode(code: 996, countryCode: "kg", countryName: "Kyrgyzstan"),
    PhoneCountryCode(code: 856, countryCode: "la", countryName: "Laos"),
    PhoneCountryCode(code: 371, countryCode: "lv", countryName: "Latvia"),
    PhoneCountryCode(code: 961, countryCode: "lb", countryName: "Lebanon"),
    PhoneCountryCode(code: 266, countryCode: "ls", countryName: "Lesotho"),
    PhoneCountryCode(code: 231, countryCode: "lr", countryName: "Liberia"),
    PhoneCountryCode(code: 218, countryCode: "ly", countryName: "Libya"),
    PhoneCountryCode(code: 423, countryCode: "li", countryName: "Liechtenstein"),
    PhoneCountryCode(code: 370, countryCode: "lt", countryName: "Lithuania"),
    PhoneCountryCode(code: 352, countryCode: "lu", countryName: "Luxembourg"),
    PhoneCountryCode(code: 853, countryCode: "mo", countryName: "Macau"),
    PhoneCountryCode(code: 389, countryCode: "mk", countryName: "Macedonia"),
    PhoneCountryCode(code: 261, countryCode: "mg", countryName: "Madagascar"),
    PhoneCountryCode(code: 265, countryCode: "mw", countryName: "Malawi"),
    PhoneCountryCode(code: 60, countryCode: "my", countryName: "Malaysia"),
    PhoneCountryCode(code: 960, countryCode: "mv", countryName: "Maldives"),
    PhoneCountryCode(code: 223, countryCode: "ml", countryName: "Mali"),
    PhoneCountryCode(code: 356, countryCode: "mt", countryName: "Malta"),
    PhoneCountryCode(code: 692, countryCode: "mh", countryName: "Marshall Islands"),
    PhoneCountryCode(code: 596, countryCode: "mq", countryName: "Martinique"),
    PhoneCountryCode(code: 222, countryCode: "mr", countryName: "Mauritania"),
    PhoneCountryCode(code: 230, countryCode: "mu", countryName: "Mauritius"),
    PhoneCountryCode(code: 52, countryCode: "mx", countryName: "Mexico"),
    PhoneCountryCode(code: 691, countryCode: "fm", countryName: "Micronesia"),
    PhoneCountryCode(code: 373, countryCode: "md", countryName: "Moldova"),
    PhoneCountryCode(code: 377, countryCode: "mc", countryName: "Monaco"),
    PhoneCountryCode(code: 976, countryCode: "mn", countryName: "Mongolia"),
    PhoneCountryCode(code: 382, countryCode: "me", countryName: "Montenegro"),
    PhoneCountryCode(code: 212, countryCode: "ma", countryName: "Morocco"),
    PhoneCountryCode(code: 258, countryCode: "mz", countryName: "Mozambique"),
    PhoneCountryCode(code: 95, countryCode: "mm", countryName: "Myanmar"),
    PhoneCountryCode(code: 264, countryCode: "na", countryName: "Namibia"),
    PhoneCountryCode(code: 674, countryCode: "nr", countryName: "Nauru"),
    PhoneCountryCode(code: 977, countryCode: "np", countryName: "Nepal"),
    PhoneCountryCode(code: 31, countryCode: "nl", countryName: "Netherlands"),
    PhoneCountryCode(code: 687, countryCode: "nc", countryName: "New Caledonia"),
    PhoneCountryCode(code: 64, countryCode: "nz", countryName: "New Zealand"),
    PhoneCountryCode(code: 505, countryCode: "ni", countryName: "Nicaragua"),
    PhoneCountryCode(code: 227, countryCode: "ne", countryName: "Niger"),
    PhoneCountryCode(code: 234, countryCode: "ng", countryName: "Nigeria"),
    PhoneCountryCode(code: 850, countryCode: "kp", countryName: "North Korea"),
    PhoneCountryCode(code: 47, countryCode: "no", countryName: "Norway"),
    PhoneCountryCode(code: 968, countryCode: "om", countryName: "Oman"),
    PhoneCountryCode(code: 92, countryCode: "pk", countryName: "Pakistan"),
    PhoneCountryCode(code: 680, countryCode: "pw", countryName: "Palau"),
    PhoneCountryCode(code: 970, countryCode: "ps", countryName: "Palestine"),
    PhoneCountryCode(code: 507, countryCode: "pa", countryName: "Panama"),
    PhoneCountryCode(code: 675, countryCode: "pg", countryName: "Papua New Guinea"),
    PhoneCountryCode(code: 595, countryCode: "py", countryName: "Paraguay"),
    PhoneCountryCode(code: 51, countryCode: "pe", countryName: "Peru"),
    PhoneCountryCode(code: 63, countryCode: "ph", countryName: "Philippines"),
    PhoneCountryCode(code: 48, countryCode: "pl", countryName: "Poland"),
    PhoneCountryCode(code: 351, countryCode: "pt", countryName: "Portugal"),
    PhoneCountryCode(code: 1, countryCode: "pr", countryName: "Puerto Rico"),
    PhoneCountryCode(code: 974, countryCode: "qa", countryName: "Qatar"),
    PhoneCountryCode(code: 262, countryCode: "re", countryName: "Réunion"),
    PhoneCountryCode(code: 40, countryCode: "ro", countryName: "Romania"),
    PhoneCountryCode(code: 7, countryCode: "ru", countryName: "Russia"),
    PhoneCountryCode(code: 250, countryCode: "rw", countryName: "Rwanda"),
    PhoneCountryCode(code: 685, countryCode: "ws", countryName: "Samoa"),
    PhoneCountryCode(code: 378, countryCode: "sm", countryName: "San Marino"),
    PhoneCountryCode(code: 239, countryCode: "st", countryName: "São Tomé and Príncipe"),
    PhoneCountryCode(code: 966, countryCode: "sa", countryName: "Saudi Arabia"),
    PhoneCountryCode(code: 221, countryCode: "sn", countryName: "Senegal"),
    PhoneCountryCode(code: 381, countryCode: "rs", countryName: "Serbia"),
    PhoneCountryCode(code: 248, countryCode: "sc", countryName: "Seychelles"),
    PhoneCountryCode(code: 232, countryCode: "sl", countryName: "Sierra Leone"),
    PhoneCountryCode(code: 65, countryCode: "sg", countryName: "Singapore"),
    PhoneCountryCode(code: 421, countryCode: "sk", countryName: "Slovakia"),
    PhoneCountryCode(code: 386, countryCode: "si", countryName: "Slovenia"),
    PhoneCountryCode(code: 677, countryCode: "sb", countryName: "Solomon Islands"),
    PhoneCountryCode(code: 252, countryCode: "so", countryName: "Somalia"),
    PhoneCountryCode(code: 27, countryCode: "za", countryName: "South Africa"),
    PhoneCountryCode(code: 82, countryCode: "kr", countryName: "South Korea"),
    PhoneCountryCode(code: 211, countryCode: "ss", countryName: "South Sudan"),
    PhoneCountryCode(code: 34, countryCode: "es", countryName: "Spain"),
    PhoneCountryCode(code: 94, countryCode: "lk", countryName: "Sri Lanka"),
    PhoneCountryCode(code: 249, countryCode: "sd", countryName: "Sudan"),
    PhoneCountryCode(code: 597, countryCode: "sr", countryName: "Suriname"),
    PhoneCountryCode(code: 268, countryCode: "sz", countryName: "Swaziland"),
    PhoneCountryCode(code: 46, countryCode: "se", countryName: "Sweden"),
    PhoneCountryCode(code: 41, countryCode: "ch", countryName: "Switzerland"),
    PhoneCountryCode(code: 963, countryCode: "sy", countryName: "Syria"),
    PhoneCountryCode(code: 886, countryCode: "tw", countryName: "Taiwan"),
    PhoneCountryCode(code: 992, countryCode: "tj", countryName: "Tajikistan"),
    PhoneCountryCode(code: 255, countryCode: "tz", countryName: "Tanzania"),
    PhoneCountryCode(code: 66, countryCode: "th", countryName: "Thailand"),
    PhoneCountryCode(code: 670, countryCode: "tl", countryName: "Timor-Leste"),
    PhoneCountryCode(code: 228, countryCode: "tg", countryName: "Togo"),
    PhoneCountryCode(code: 676, countryCode: "to", countryName: "Tonga"),
    PhoneCountryCode(code: 216, countryCode: "tn", countryName: "Tunisia"),
    PhoneCountryCode(code: 90, countryCode: "tr", countryName: "Turkey"),
    PhoneCountryCode(code: 993, countryCode: "tm", countryName: "Turkmenistan"),
    PhoneCountryCode(code: 688, countryCode: "tv", countryName: "Tuvalu"),
    PhoneCountryCode(code: 256, countryCode: "ug", countryName: "Uganda"),
    PhoneCountryCode(code: 380, countryCode: "ua", countryName: "Ukraine"),
    PhoneCountryCode(code: 971, countryCode: "ae", countryName: "United Arab Emirates"),
    PhoneCountryCode(code: 44, countryCode: "gb", countryName: "United Kingdom"),
    PhoneCountryCode(code: 1, countryCode: "us", countryName: "United States"),
    PhoneCountryCode(code: 598, countryCode: "uy", countryName: "Uruguay"),
    PhoneCountryCode(code: 998, countryCode: "uz", countryName: "Uzbekistan"),
    PhoneCountryCode(code: 678, countryCode: "vu", countryName: "Vanuatu"),
    PhoneCountryCode(code: 39, countryCode: "va", countryName: "Vatican City"),
    PhoneCountryCode(code: 58, countryCode: "ve", countryName: "Venezuela"),
    PhoneCountryCode(code: 84, countryCode: "vn", countryName: "Vietnam"),
    PhoneCountryCode(code: 967, countryCode: "ye", countryName: "Yemen"),
    PhoneCountryCode(code: 260, countryCode: "zm", countryName: "Zambia"),
    PhoneCountryCode(code: 263, countryCode: "zw", countryName: "Zimbabwe")
]
